---
toc: false
title: "Contact"
pagetitle: "Contact"
---

Bambi is dedicated to providing a harassment-free community for everyone, regardless of gender,
sexual orientation, gender identity, and expression, disability, physical appearance, 
body size, race, or religion. We do not tolerate harassment of community members in any form.

However, it is not uncommon to suffer or witness abusive behaviors online. 
If you have experienced or witnessed any behaviour that violates our 
[Code of Conduct](https://github.com/bambinos/bambi/blob/main/CODE_OF_CONDUCT.md), 
we encourage you to report it through the form below.

When reporting an incident, please provide as much detail as possible, including:

* The approximate date, time and location of the incident (please be as specific as possible).
* Any identifying information of the individual whose behavior is being reported (e.g. name, nickname, screen name, physical description).
* A description of the behavior, your account of what happened, and any available supporting records (e.g. email, GitHub issue url, screenshots, etc.).
* If reporting harassing language, please be specific about the words used.
* A description of the circumstances/context surrounding the incident.
* Is the incident ongoing, and/or is this part of an ongoing pattern of behavior by this individual?
* Did anyone else observe the incident? If possible, please provide names and contact info of anyone else who witnessed or was involved in this incident.
* Any other information you believe we should have about what happened or that you'd like us to know.

**All the information be kept confidential**. 
If you wish to remain anonymous, your information will not be shared beyond the person 
receiving the initial report.

We take every report of Code of Conduct violations very seriously and will handle each one
with care and confidentiality. If you're unsure whether certain behavior is a violation, 
or if you need help with the reporting process, don't hesitate to reach out to us. 
We are here to help and support you.

```{=html}
<form action="https://public.herotofu.com/v1/3f06ee10-1515-11ef-a449-3b7e66789316" method="post" accept-charset="UTF-8" class="bambi-form">
    <input name="name" id="name" type="text" class="feedback-input" placeholder="Name" required>
    <input name="email" id="email" type="email" class="feedback-input" placeholder="E-mail" required>
    <textarea name="text" class="feedback-input" placeholder="Your message" required></textarea>
  <div>
    <input type="submit" value="SUBMIT" class="form-submit"/>
    <div style="text-indent:-99999px; white-space:nowrap; overflow:hidden; position:absolute;" aria-hidden="true">
      <input type="text" name="_gotcha" tabindex="-1" autocomplete="off" />
    </div>
  </div>
</form>
```

<br>

Form adapted from the [JAXGP Contact Form](https://jaxgaussianprocesses.com/contact/) 
and the [NumFOCUS Reporting Form](https://numfocus.typeform.com/to/ynjGdT).
