---
title: "Frequently Asked Questions"
pagetitle: "FAQ"
toc: false
---

## General Questions

### What is the difference between Bambi and PyMC?

* Bambi is a regression library built on top of PyMC. It provides a simple interface for 
specifying Bayesian models, and allows for easy inference using MCMC or variational 
inference.
* PyMC is a library for Bayesian modelling, and is the backend used by Bambi. 
It is a very powerful library, but can be challenging to use for beginners. 
Bambi provides a simple interface for specifying models, and allows for easy inference via

### Why have a Bayesian regression library?

Bayesian modelling allows flexible (read 'bespoke') model specification and also provides an
estimation of uncertainty in the model parameters. Both of these are wildly useful in
practice, in particular in a business context where the model is used to make decisions,
and where a complex model may be needed to capture the underlying relationships. Further,
Bayesian modelling allows graceful handling of small sample sizes by judicious use of
prior distributions.

###

## Inference Questions

### What sampling methods are available?

The sampler used is automatically selected given the type of variables used in the model.
For inference, Bambi supports both MCMC and variational inference. 
MCMC is the default, but you can specify variational inference by passing 
`inference_method='vi'` to `Model.fit()`.
Bambi also supports multiple backends for MCMC, including NumPyro, and BlackJax. 
See API for "fit" method for more details [here](https://bambinos.github.io/bambi/api/Model.html#bambi.Model.fit).

### Can inference in Bambi be sped up using GPUs/TPUs?

Yes, Bambi supports inference on GPUs and TPUs using the numpyro and blackjax backends. 
See the API for "fit" method for more details 
[here](https://bambinos.github.io/bambi/api/Model.html#bambi.Model.fit).

### My sampler through errors/indicating divergences, what should I do?

* Divergences are a common issue in Bayesian modelling, and are usually not a problem as long as
they are not prevalent. However, if you are seeing a lot of divergences, you may want
to try 1) respecifying your model, 2) a different sampler.
* If the sampler fails, this is likely an issue with model specification. Make sure you are using
the correct priors for your model, and that you are not specifying a prior that is too
strong (e.g. a prior that is too narrow), or one that does not match the data (e.g. a
prior that doesn't cover the domain of the data such as using a HalfNormal prior for a
parameter that can be negative).


## Model Specification Questions

### My data has a non-normal distributions, can I still use Bambi?

Yes, Bambi supports a wide range of distributions which can be specified using the "family"
argument to the "Model". You can find examples of how to specify these distributions 
in the [Bambi examples](https://bambinos.github.io/bambi/notebooks/).

### How do I find out what priors are available?

You can use any valid PyMC distribution as a prior. 
You can find a list of all the distributions available in PyMC [here](https://www.pymc.io/projects/docs/en/stable/api/distributions.html).
You can also find examples of how to specify priors in the [Bambi examples](https://bambinos.github.io/bambi/notebooks/),
 and in the [Getting Started Guide](https://bambinos.github.io/bambi/notebooks/getting_started.html#Specifying-priors).

### Does bambi come with pre-specified regression models?

To allow building of bespoke models, Bambi does not come with pre-specified regression models.
However, you can find examples of how to specify models in the 
[Bambi examples](https://bambinos.github.io/bambi/notebooks/).
