# Formula { #bambi.Formula }

```python
Formula(formula, *additionals)
```

Model formula

Allows to describe a model with multiple formulas. The first formula describes the response
variable and its predictors. The following formulas describe predictors for other parameters
of the likelihood function, allowing distributional models.

## Parameters {.doc-section .doc-section-parameters}

| Name         | Type         | Description                                                                         | Default    |
|--------------|--------------|-------------------------------------------------------------------------------------|------------|
| formula      | str          | A model description written using the formula syntax from the `formulae` library.   | _required_ |
| *additionals | tuple of str | Additional formulas that describe model parameters rather than a response variable. | `()`       |

## Methods

| Name | Description |
| --- | --- |
| [check_additional](#bambi.Formula.check_additional) | Check if an additional formula matches the expected format |
| [check_additionals](#bambi.Formula.check_additionals) | Check if the additional formulas match the expected format |
| [get_all_formulas](#bambi.Formula.get_all_formulas) | Get all the model formulas |

### check_additional { #bambi.Formula.check_additional }

```python
Formula.check_additional(additional)
```

Check if an additional formula matches the expected format

#### Parameters {.doc-section .doc-section-parameters}

| Name       | Type   | Description                                       | Default    |
|------------|--------|---------------------------------------------------|------------|
| additional | str    | A model formula that describes a model parameter. | _required_ |

#### Raises {.doc-section .doc-section-raises}

| Name   | Type       | Description                                      |
|--------|------------|--------------------------------------------------|
|        | ValueError | If the formula does not contain a response term. |
|        | ValueError | If the response term is not a plain name.        |

### check_additionals { #bambi.Formula.check_additionals }

```python
Formula.check_additionals(additionals)
```

Check if the additional formulas match the expected format

#### Parameters {.doc-section .doc-section-parameters}

| Name        | Type            | Description                                                                    | Default    |
|-------------|-----------------|--------------------------------------------------------------------------------|------------|
| additionals | Sequence\[str\] | Model formulas that describe model parameters rather than a response variable. | _required_ |

#### Returns {.doc-section .doc-section-returns}

| Name        | Type            | Description                                                 |
|-------------|-----------------|-------------------------------------------------------------|
| additionals | Sequence\[str\] | If all formulas match the required format, it returns them. |

### get_all_formulas { #bambi.Formula.get_all_formulas }

```python
Formula.get_all_formulas()
```

Get all the model formulas

#### Returns {.doc-section .doc-section-returns}

| Name   | Type   | Description                       |
|--------|--------|-----------------------------------|
|        | list   | All the formulas in the instance. |