---
title: Bambi

---

## Model

The basics

| | |
| --- | --- |
| [Model](Model.qmd#bambi.Model) | Specification of model class |
| [Formula](Formula.qmd#bambi.Formula) | Model formula |

## Setting up priors



| | |
| --- | --- |
| [Prior](Prior.qmd#bambi.Prior) | Abstract specification of a term prior |

## Custom families



| | |
| --- | --- |
| [Family](Family.qmd#bambi.Family) | A specification of model family |
| [Likelihood](Likelihood.qmd#bambi.Likelihood) | Representation of a Likelihood function for a Bambi model |
| [Link](Link.qmd#bambi.Link) | Representation of a link function |

## Plots



| | |
| --- | --- |
| [interpret.plot_comparisons](interpret.plot_comparisons.qmd#bambi.interpret.plot_comparisons) | Plot conditional adjusted comparisons. |
| [interpret.plot_predictions](interpret.plot_predictions.qmd#bambi.interpret.plot_predictions) | Plot conditional adjusted predictions. |
| [interpret.plot_slopes](interpret.plot_slopes.qmd#bambi.interpret.plot_slopes) | Plot conditional adjusted slopes. |

## Interpretations



| | |
| --- | --- |
| [interpret.comparisons](interpret.comparisons.qmd#bambi.interpret.comparisons) | Compute conditional adjusted comparisons. |
| [interpret.predictions](interpret.predictions.qmd#bambi.interpret.predictions) | Compute conditional adjusted predictions. |
| [interpret.slopes](interpret.slopes.qmd#bambi.interpret.slopes) | Compute conditional adjusted slopes. |

## Data



| | |
| --- | --- |
| [clear_data_home](clear_data_home.qmd#bambi.clear_data_home) | Delete all the content of the data home cache. |
| [load_data](load_data.qmd#bambi.load_data) | Load a dataset. |