# interpret.predictions { #bambi.interpret.predictions }

`interpret.predictions(model, idata, conditional=None, average_by=None, target='mean', pps=False, use_hdi=True, prob=None, transforms=None, sample_new_groups=False)`

Compute Conditional Adjusted Predictions

## Parameters

| Name                | Type                           | Description                                                                                                                                                                                                                            | Default    |
|---------------------|--------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| `model`             | bambi.Model                    | The model for which we want to plot the predictions.                                                                                                                                                                                   | _required_ |
| `idata`             | arviz.InferenceData            | The InferenceData object that contains the samples from the posterior distribution of the model.                                                                                                                                       | _required_ |
| `conditional`       | (str, list, dict)              | The covariates we would like to condition on. If dict, keys are the covariate names and values are the values to condition on.                                                                                                         | `None`     |
| `average_by`        | Union\[str, list, bool, None\] | The covariates we would like to average by. The passed covariate(s) will marginalize over the other covariates in the model. If True, it averages over all covariates in the model to obtain the average estimate. Defaults to `None`. | `None`     |
| `target`            | str                            | Which model parameter to plot. Defaults to 'mean'. Passing a parameter into target only works when pps is False as the target may not be available in the posterior predictive distribution.                                           | `'mean'`   |
| `pps`               | bool                           | Whether to plot the posterior predictive samples. Defaults to `False`.                                                                                                                                                                 | `False`    |
| `use_hdi`           | bool                           | Whether to compute the highest density interval (defaults to True) or the quantiles.                                                                                                                                                   | `True`     |
| `prob`              | float                          | The probability for the credibility intervals. Must be between 0 and 1. Defaults to 0.94. Changing the global variable `az.rcParam["stats.hdi_prob"]` affects this default.                                                            | `None`     |
| `transforms`        | dict                           | Transformations that are applied to each of the variables being plotted. The keys are the name of the variables, and the values are functions to be applied. Defaults to `None`.                                                       | `None`     |
| `sample_new_groups` | bool                           | If the model contains group-level effects, and data is passed for unseen groups, whether to sample from the new groups. Defaults to `False`.                                                                                           | `False`    |

## Returns

| Type             | Description                                                   |
|------------------|---------------------------------------------------------------|
| pandas.DataFrame | A DataFrame with the `create_cap_data` and model predictions. |

## Raises

| Type       | Description                                                                                                                                 |
|------------|---------------------------------------------------------------------------------------------------------------------------------------------|
| ValueError | If `pps` is `True` and `target` is not `"mean"`. If `conditional` is a list and the length is greater than 3. If `prob` is not > 0 and < 1. |